version: '3.7'
services:
  back-end:
    container_name: Back-MinecraftRpPoliceIntra
    build:
      context: ./back-end
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      PORT: 8080
      DB_NAME: "police"
      DB_USER: "admin"
      DB_PASSWORD: "123456"
      DB_HOST: "postgres"
      DB_DRIVER: "postgres"
    ports:
      - "8080:8080"
    networks:
      - back-tier
    volumes:
      - ./back-end/src/:/src

  postgres:
    image: postgres
    restart: always
    networks: 
      - back-tier
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: "police"

networks:
  back-tier:

volumes:
  db-data: