version: '3.7'
services:
  back-end:
    container_name: Back-MinecraftRpPoliceIntra
    build:
      context: ./back-end
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      PORT: 8080
    env_file:
     - ./.env
    ports:
      - "8080:8080"
    networks:
      - back-tier
    volumes:
      - ./back-end/src/:/src

  postgres:
    image: postgres
    restart: always
    networks: 
      - back-tier
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    env_file:
     - ./.envDB

  client:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - back-tier
    volumes:
      - ./front-end/:/app
    depends_on:
      - back-end
    environment:
      PORT: 3000

networks:
  back-tier:

volumes:
  db-data: